all:
	clang++ -std=c++14 -O0 -fpermissive -rdynamic -fPIC addone.cpp -o addone ${ZE_SHARED_LOADER} -L/home/quinn/nod/level-zero/build/lib -lstdc++ -lze_loader 
	clang++ -std=c++14 -O0 -fpermissive -rdynamic -fPIC addonescalar.cpp -o addonescalar ${ZE_SHARED_LOADER} -L/home/quinn/nod/level-zero/build/lib -lstdc++ -lze_loader 
