all:
	clang++ -std=c++14 -O0 -fpermissive -rdynamic -fPIC fill.cpp -o fill ${ZE_SHARED_LOADER} -L/home/quinn/nod/level-zero/build/lib -lstdc++ -lze_loader 
	clang++ -std=c++14 -O0 -fpermissive -rdynamic -fPIC fillscalar.cpp -o fillscalar ${ZE_SHARED_LOADER} -L/home/quinn/nod/level-zero/build/lib -lstdc++ -lze_loader 
